import { db, usersTable, accountsTable, type Account } from "@workspace/db";
import { and, eq, isNotNull } from "drizzle-orm";
import { getAIClient, AI_MODEL } from "./aiClient";
import { extractJson, userLabels } from "./aiLabeling";
import { clientForAccount } from "./google";
import {
  listEmails,
  listLabels,
  sendEmail,
  type ApiEmail,
  type ApiLabel,
} from "./gmail";
import { logger } from "./logger";

interface DigestSection {
  label: ApiLabel;
  emails: ApiEmail[];
}

interface DigestSectionSummary {
  label: string;
  summary: string;
  items: Array<{ subject: string; sender: string; summary: string }>;
}

export interface DailyDigestRunResult {
  accountId: number;
  sections: number;
  emails: number;
  sent: boolean;
}

const MAX_LABELS_PER_ACCOUNT = 10;
const MAX_EMAILS_PER_LABEL = 6;

function digestCursor(account: Account): Date {
  return account.dailyDigestCursor ?? new Date(Date.now() - 24 * 60 * 60 * 1000);
}

function gmailAfterQuery(cursor: Date): string {
  return `is:unread after:${Math.floor(cursor.getTime() / 1000)}`;
}

function formatDate(d = new Date()): string {
  return d.toISOString().slice(0, 10);
}

async function buildSections(
  auth: ReturnType<typeof clientForAccount>,
  account: Account,
): Promise<DigestSection[]> {
  const since = gmailAfterQuery(digestCursor(account));
  const labels = userLabels(await listLabels(auth)).slice(0, MAX_LABELS_PER_ACCOUNT);
  const sections: DigestSection[] = [];

  for (const label of labels) {
    const emails = await listEmails(
      auth,
      { labelId: label.id, search: since },
      MAX_EMAILS_PER_LABEL,
    );
    if (emails.length > 0) sections.push({ label, emails });
  }

  return sections;
}

async function summarizeSections(
  sections: DigestSection[],
): Promise<DigestSectionSummary[]> {
  const prompt = `Summarize these unread emails into a daily digest grouped by label.

${sections
  .map(
    (section, sectionIndex) => `Label ${sectionIndex}: ${section.label.name}
${section.emails
  .map(
    (email, emailIndex) =>
      `[${sectionIndex}.${emailIndex}] From: ${email.sender} <${email.senderEmail}>
Subject: ${email.subject}
Body: ${(email.body || email.snippet).slice(0, 700)}`,
  )
  .join("\n\n")}`,
  )
  .join("\n\n")}

Return a JSON array with one object per label:
{"label":"<label name>","summary":"<1-2 sentence label summary>","items":[{"subject":"<subject>","sender":"<sender>","summary":"<one sentence>"}]}
Keep it concise and practical. JSON only.`;

  const completion = await getAIClient().chat.completions.create({
    model: AI_MODEL,
    messages: [{ role: "user", content: prompt }],
  });
  const content = completion.choices[0]?.message?.content ?? "[]";
  const parsed = extractJson(content) as DigestSectionSummary[];
  if (!Array.isArray(parsed)) return [];
  return parsed.map((section) => ({
    label: String(section.label ?? ""),
    summary: String(section.summary ?? ""),
    items: Array.isArray(section.items)
      ? section.items.map((item) => ({
          subject: String(item.subject ?? ""),
          sender: String(item.sender ?? ""),
          summary: String(item.summary ?? ""),
        }))
      : [],
  }));
}

function fallbackSummaries(sections: DigestSection[]): DigestSectionSummary[] {
  return sections.map((section) => ({
    label: section.label.name,
    summary: `${section.emails.length} unread email${section.emails.length === 1 ? "" : "s"} need attention.`,
    items: section.emails.map((email) => ({
      subject: email.subject || "(no subject)",
      sender: email.sender,
      summary: email.snippet || email.body.slice(0, 140),
    })),
  }));
}

function renderDigest(account: Account, summaries: DigestSectionSummary[]): string {
  const lines = [
    `Daily Inbox AI digest for ${account.email}`,
    formatDate(),
    "",
  ];
  for (const section of summaries) {
    lines.push(`${section.label}`);
    lines.push(section.summary);
    for (const item of section.items) {
      lines.push(`- ${item.sender}: ${item.subject}`);
      if (item.summary) lines.push(`  ${item.summary}`);
    }
    lines.push("");
  }
  lines.push("Generated by Inbox AI. Remote images were not loaded to create this digest.");
  return lines.join("\n");
}

export async function runDailyDigestForAccount(
  account: Account,
): Promise<DailyDigestRunResult> {
  const auth = clientForAccount(account);
  const sections = await buildSections(auth, account);
  const emailCount = sections.reduce((n, section) => n + section.emails.length, 0);

  if (sections.length === 0) {
    await db
      .update(accountsTable)
      .set({ dailyDigestCursor: new Date(), updatedAt: new Date() })
      .where(eq(accountsTable.id, account.id));
    return { accountId: account.id, sections: 0, emails: 0, sent: false };
  }

  let summaries: DigestSectionSummary[];
  try {
    summaries = await summarizeSections(sections);
    if (summaries.length === 0) summaries = fallbackSummaries(sections);
  } catch (err) {
    logger.error({ err, accountId: account.id }, "daily digest AI summary failed");
    summaries = fallbackSummaries(sections);
  }

  await sendEmail(auth, {
    to: account.email,
    subject: `Daily Inbox AI digest - ${formatDate()}`,
    body: renderDigest(account, summaries),
  });

  await db
    .update(accountsTable)
    .set({ dailyDigestCursor: new Date(), updatedAt: new Date() })
    .where(eq(accountsTable.id, account.id));

  return {
    accountId: account.id,
    sections: sections.length,
    emails: emailCount,
    sent: true,
  };
}

export async function runDailyDigestForAllAccounts(
  opts: { maxAccounts?: number; totalBudgetMs?: number } = {},
): Promise<{ accounts: number; results: DailyDigestRunResult[] }> {
  const maxAccounts = opts.maxAccounts ?? 10;
  const totalBudgetMs = opts.totalBudgetMs ?? 25_000;

  const rows = await db
    .select({ account: accountsTable })
    .from(accountsTable)
    .innerJoin(usersTable, eq(accountsTable.userId, usersTable.id))
    .where(
      and(
        eq(usersTable.dailyDigestEnabled, true),
        isNotNull(accountsTable.refreshToken),
      ),
    )
    .limit(maxAccounts);

  const candidates = rows.map((r) => r.account);
  const results: DailyDigestRunResult[] = [];
  const startedAt = Date.now();

  for (const account of candidates) {
    if (Date.now() - startedAt > totalBudgetMs) break;
    try {
      results.push(await runDailyDigestForAccount(account));
    } catch (err) {
      logger.error({ err, accountId: account.id }, "daily digest run failed");
    }
  }

  return { accounts: candidates.length, results };
}
